### ISSUE TITLE
Crash on TicTacToe new game

### ISSUE THREAD

**Issue by vkjr** [status-im/react-native-linux#11]
**Steps to reproduce**
1. Run TicTacToe
2. Finish current game
3. press 'new game'

Crash appears on the original 'react-native-linux' branch before merging with latest 'react-native'. Need to be checked after merge.

**Comment by narek-h** [comment]
@vkjr, could you please check this with the latest changes (including PR for #18) ? 
Works without crash on my side.

**Comment by narek-h** [comment]
@vkjr, sorry. I see a crash when running from QtCreator. 
This could be relevant to release build vs debug. When building/running from command line it works without crash.

**Comment by vkjr** [comment]
@narek-h, hmm, I just tested with local changes related to redbox fix and "new game" worked fine.
