### ISSUE TITLE
TicTacToe header text in a wrong position

### ISSUE THREAD

**Issue by vkjr** [status-im/react-native-linux#33]
### Description
TicTacToe app window has a header text `EXTREME T3` that should be at the top accordingly to javascript code:

```
return (
      <View style={styles.container}>
        <Text style={styles.title}>EXTREME T3</Text>
        <View style={styles.board}>
          {rows}
        </View>
        <GameEndOverlay
          board={this.state.board}
          onRestart={this.restartGame}
        />
      </View>
    );
```

But in react-native-qt it draws at the bottom:
<img width="638" alt="screen shot 2017-08-17 at 6 25 32 pm" src="https://user-images.githubusercontent.com/5786310/29420158-d864d1ba-8379-11e7-8fff-b73327169e33.png">

**Comment by narek-h** [comment]
@vkjr , @MaxRis  since this issue is relevant to layout, it can cause other  UI issues. 
So, I think better to have this fixed quickly. I'll look on this if you don't mind  (should not take long).

**Comment by MaxRis** [comment]
@narek-h , sure, 
I think we can take any issues which are not In-Progress and not assigned to someone without prior notice. cc @vkjr
